### ISSUE TITLE
[vkBase][Feature]: объявить VK Sans Display как акцентный шрифт по умолчанию

### ISSUE THREAD

**Issue by inomdzhon** [VKCOM/vkui-tokens#376]
_Тема:_ **vkBase**

Чтобы у пользователя была возможность подключить свой шрифт.

Например,
```css
@font-face {
  font-family: "VK Sans Display";
  src: url("My Awesome Font.woff") format("woff");
}
```
